version: 1

permissions:
  tools:
    closeIssue: true
    searchIssues: true
    createIssueComment: true
    readIssueComments: true
    readIssueLabels: true
    createIssueLabel: true
    readPullRequest: true
    mergePullRequest: true

  actions:
    closeIssue:
      decision: allow
      condition:
        issues:
          labels:
            any:
              - 'duplicate'
              - 'invalid'

    mergePullRequest:
      decision: allow
      condition:
        pullRequest:
          author: 'dependabot[bot]'
          updateType:
            in: [minor, patch]
